# Generated by Django 5.2.17 on 2026-09-24 17:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='defaults/default.png', upload_to='motoristas/')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('num_cnh', models.CharField(max_length=20)),
                ('tipo_cnh', models.CharField(choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E')], max_length=1)),
                ('tipo_sangue', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('cel', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('ingresso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('duracao', models.DurationField()),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('motoristas', models.ManyToManyField(related_name='rotas', to='RuyFrotas.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('atendida', models.BooleanField(default=False)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='RuyFrotas.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='defaults/default.png', upload_to='veiculos/')),
                ('apelido', models.CharField(max_length=300)),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=100)),
                ('tipo_combustivel', models.CharField(choices=[('G', 'Gasolina'), ('A', 'Álcool'), ('D', 'Diesel'), ('F', 'Flex'), ('E', 'Veículo Elétrico')], max_length=1)),
                ('tipo_cambio', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático'), ('AUTOMATIZADO', 'Automatizado'), ('CVT', 'CVT'), ('DCT', 'Dupla embreagem (DCT)')], max_length=12)),
                ('quilometragem', models.IntegerField()),
                ('capacidade', models.IntegerField()),
                ('observacao', models.TextField()),
                ('is_funcionando', models.BooleanField(default=True)),
                ('is_quebrado', models.BooleanField(default=False)),
                ('is_conserto', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('FUNCIONANDO', 'Funcionando'), ('QUEBRADO', 'Quebrado'), ('CONSERTO', 'Em conserto')], default='FUNCIONANDO', max_length=11)),
                ('motoristas', models.ManyToManyField(related_name='veiculos', to='RuyFrotas.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('atendida', models.BooleanField(default=False)),
                ('gasto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='RuyFrotas.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=300)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='RuyFrotas.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('data_chegada', models.DateTimeField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='RuyFrotas.motorista')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='RuyFrotas.rota')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='RuyFrotas.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='motorista',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to=settings.AUTH_USER_MODEL),
        ),
    ]
