# Generated by Django 5.2.17 on 2026-08-29 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('num_cnh', models.CharField(max_length=20)),
                ('tipo_cnh', models.CharField(choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E')], max_length=1)),
                ('tipo_sangue', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('cel', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('ingresso', models.DateField()),
                ('saiu', models.BooleanField(default=False)),
                ('chegou', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('duracao', models.DurationField()),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('motoristas', models.ManyToManyField(related_name='rotas', to='RuyFrotas.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('atendida', models.BooleanField(default=False)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='RuyFrotas.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=300)),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=100)),
                ('tipo_combustivel', models.CharField(choices=[('G', 'Gasolina'), ('A', 'Álcool'), ('D', 'Diesel'), ('F', 'Flex'), ('E', 'Veículo Elétrico')], max_length=1)),
                ('tipo_cambio', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático'), ('AUTOMATIZADO', 'Automatizado'), ('CVT', 'CVT'), ('DCT', 'Dupla embreagem (DCT)')], max_length=12)),
                ('quilometragem', models.IntegerField()),
                ('capacidade', models.IntegerField()),
                ('observacao', models.TextField()),
                ('is_funcionando', models.BooleanField(default=True)),
                ('is_quebrado', models.BooleanField(default=False)),
                ('is_conserto', models.BooleanField(default=False)),
                ('motoristas', models.ManyToManyField(related_name='veiculos', to='RuyFrotas.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('atendida', models.BooleanField(default=False)),
                ('gasto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='RuyFrotas.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=300)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='RuyFrotas.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('data_chegada', models.DateTimeField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='RuyFrotas.motorista')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='RuyFrotas.rota')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='RuyFrotas.veiculo')),
            ],
        ),
    ]
