# Generated by Django 5.2.17 on 2026-08-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuyFrotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='chegou',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='saiu',
        ),
        migrations.AddField(
            model_name='motorista',
            name='foto',
            field=models.ImageField(default='defaults/default.png', upload_to='motoristas/'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(default='defaults/default.png', upload_to='veiculos/'),
        ),
    ]
