# Generated by Django 5.2.17 on 2026-09-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuyFrotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('FUNCIONANDO', 'Funcionando'), ('QUEBRADO', 'Quebrado'), ('CONSERTO', 'Em conserto')], default='FUNCIONANDO', max_length=11),
        ),
    ]
