# Generated by Django 5.2.17 on 2026-09-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RuyFrotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='is_conserto',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='is_funcionando',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='is_quebrado',
        ),
    ]
