# Generated by Django 5.2.17 on 2026-10-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuyFrotas', '0002_remove_veiculo_is_conserto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MOTORISTA', 'Motorista')], default='MOTORISTA', max_length=20),
        ),
    ]
